[uwsgi]
socket = 127.0.0.1:8080
wsgi-file = server.py
callable = app
master = true
processes = 4
threads = 2
vacuum = true
die-on-term = true
chmod-socket = 660
stats = 127.0.0.1:9191
lazy-apps = true
log-master = true
logto = /var/log/uwsgi/uwsgi.log
#log-maxsize = 20971520
#log-backupname = /var/log/uwsgi/old-uwsgi.log
touch-logreopen = /var/log/uwsgi/uwsgi-touch-logreopen.touch
